{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7a614f7f",
   "metadata": {},
   "outputs": [],
   "source": [
    "# analysis.py\n",
    "\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "from wordcloud import WordCloud\n",
    "\n",
    "# Load the dataset\n",
    "df = pd.read_csv('metadata.csv', low_memory=False)\n",
    "\n",
    "# Basic exploration\n",
    "print(\"Shape:\", df.shape)\n",
    "print(df.info())\n",
    "print(df.isnull().sum())\n",
    "\n",
    "# Data cleaning\n",
    "df_clean = df[['title', 'abstract', 'publish_time', 'journal', 'source_x']].copy()\n",
    "df_clean['publish_time'] = pd.to_datetime(df_clean['publish_time'], errors='coerce')\n",
    "df_clean['year'] = df_clean['publish_time'].dt.year\n",
    "df_clean['abstract_word_count'] = df_clean['abstract'].fillna('').apply(lambda x: len(x.split()))\n",
    "\n",
    "# Analysis: Publications by year\n",
    "year_counts = df_clean['year'].value_counts().sort_index()\n",
    "plt.figure(figsize=(8, 4))\n",
    "sns.barplot(x=year_counts.index, y=year_counts.values)\n",
    "plt.title('Publications by Year')\n",
    "plt.xlabel('Year')\n",
    "plt.ylabel('Number of Papers')\n",
    "plt.tight_layout()\n",
    "plt.savefig('publications_by_year.png')\n",
    "plt.close()\n",
    "\n",
    "# Top journals\n",
    "top_journals = df_clean['journal'].value_counts().head(10)\n",
    "plt.figure(figsize=(8, 4))\n",
    "top_journals.plot(kind='barh', color='skyblue')\n",
    "plt.title('Top Journals Publishing COVID-19 Research')\n",
    "plt.xlabel('Number of Papers')\n",
    "plt.tight_layout()\n",
    "plt.savefig('top_journals.png')\n",
    "plt.close()\n",
    "\n",
    "# Word cloud of titles\n",
    "titles = ' '.join(df_clean['title'].dropna())\n",
    "wordcloud = WordCloud(width=800, height=400, background_color='white').generate(titles)\n",
    "plt.figure(figsize=(10, 5))\n",
    "plt.imshow(wordcloud, interpolation='bilinear')\n",
    "plt.axis('off')\n",
    "plt.title('Frequent Words in Paper Titles')\n",
    "plt.tight_layout()\n",
    "plt.savefig('title_wordcloud.png')\n",
    "plt.close()\n",
    "\n",
    "print(\"Analysis complete. Visualizations saved.\")\n"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
